version: '3.8'

services:
  postgres:
    image: postgres
    container_name: smartnotes-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smartnotes
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: smartnotes-backend
    volumes:
      - ./backend:/app
    working_dir: /app
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/smartnotes
    command: >
      sh -c "
        npx prisma migrate deploy;
        npx ts-node-dev --respawn --transpile-only src/index.ts
      "

  frontend:
    build: ./frontend
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app  
      - /app/node_modules


volumes:
  pgdata:
